import { WireframeHeader, WireframeMetric, WireframeSection } from "@/components/WireframeShell";

function SalesCharts() {
  return <div className="grid gap-6 xl:grid-cols-2"><WireframeSection title="Lead trend · 7 วัน"><div className="flex h-48 items-end gap-3 border-b-2 border-l-2 border-slate-300 px-4">{[["Mon","35%","4"],["Tue","55%","6"],["Wed","45%","5"],["Thu","70%","8"],["Fri","85%","10"],["Sat","62%","7"],["Sun","92%","11"]].map(([day,height,value]) => <div key={day} className="flex h-full flex-1 flex-col items-center justify-end gap-2"><span className="text-xs text-slate-500">{value}</span><div className="w-full max-w-10 bg-slate-900" style={{ height }} /><span className="text-xs text-slate-500">{day}</span></div>)}</div></WireframeSection><WireframeSection title="Lead source"><div className="grid gap-4">{[["Website Form","36%","20"],["Facebook","27%","15"],["LINE","21%","12"],["Referral","16%","9"]].map(([source,percent,count]) => <div key={source}><div className="flex justify-between text-sm"><span className="font-bold">{source}</span><span className="text-slate-500">{count} leads · {percent}</span></div><div className="mt-2 h-3 bg-slate-200"><div className="h-3 bg-slate-900" style={{ width: percent }} /></div></div>)}</div></WireframeSection></div>;
}

export default function SalesDashboardPage() {
  return <WireframeHeader area="CRM & Customer" title="Sales Dashboard" role="Sales"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><WireframeMetric label="New leads" value="18" detail="วันนี้เพิ่มขึ้น 12%" /><WireframeMetric label="Lead conversion" value="32%" detail="เทียบกับเดือนก่อน +6%" /><WireframeMetric label="Pipeline value" value="฿2.8M" detail="24 active deals" /><WireframeMetric label="Customer health" value="75%" detail="ลูกค้าที่อยู่ในสถานะปกติ" /></div><div className="mt-6"><SalesCharts /></div><div className="mt-6 grid gap-6 xl:grid-cols-2"><WireframeSection title="Sales insight"><div className="grid gap-3 text-sm"><p className="border-b border-slate-200 pb-3">Website Form เป็นแหล่ง Lead สูงสุดในสัปดาห์นี้</p><p className="border-b border-slate-200 pb-3">Deal มูลค่ารวม ฿1.24M มีโอกาสปิดภายในเดือนนี้</p><p>Lead conversion เพิ่มขึ้นจากเดือนก่อน 6%</p></div></WireframeSection><WireframeSection title="Customer insight"><div className="grid gap-3 text-sm"><p className="border-b border-slate-200 pb-3">ลูกค้า 6 รายต้องได้รับการดูแลเพิ่มเติม</p><p className="border-b border-slate-200 pb-3">มี Contract ใกล้หมดอายุ 3 ราย</p><p>มี Ticket ที่กระทบความพึงพอใจ 2 ราย</p></div></WireframeSection></div></WireframeHeader>;
}
